export enum IconName {
    humidity = 'humidity',
    lighting = 'lighting',
    temperature = 'temperature',
    heart = 'heart',
    heartBig = 'heart-big',
    heartFilled = 'heart-filled',
    heartBigFilled = 'heart-big-filled',
    closeCross = 'close-cross',
    list = 'list',
    arrowBackward = 'arrow-backward',
    arrowForward = 'arrow-forward',
    listShort = 'list-short',
    minus = 'minus',
    plus = 'plus',
    vk = 'vk',
    fb = 'fb',
    instagram = 'instagram',
    swiperBackward = 'swiper-backward',
    swiperBackwardGray = 'swiper-backward-gray',
    swiperForward = 'swiper-forward',
    swiperForwardGray = 'swiper-forward-gray',
    dots = 'dots',
    login = 'login',
    profile = 'profile',
    cart = 'cart'
}